# @package _global_
hydra:
  sweeper:
    ax_config:
      max_trials: 10
      params:
        strategy.algorithm.popsize:
          type: range
          bounds: [10, 100]
        strategy.evoparams.mutate_best_vector:
          type: bool
        strategy.evoparams.num_diff_vectors:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.cross_over_rate:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.diff_w:
          type: range
          bounds: [0.0, 2.0]

strategy:
  name: DE
  algorithm:
    _target_: evosax.strategies.DE
    popsize: ${general.popsize}
    num_dims: null
    pholder_params: null
    n_devices: null
  evoparams:
    mutate_best_vector: True
    num_diff_vectors: 1
    cross_over_rate: 0.9
    diff_w: 0.8
    init_min: 0.0
    init_max: 1.0
    clip_min: 0.0
    clip_max: 1.0
