# @package _global_
hydra:
  sweeper:
    ax_config:
      max_trials: 10
      params:
        strategy.algorithm.popsize:
          type: range
          bounds: [10, 100]
        strategy.algorithm.mean_decay:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.radius_max:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.radius_min:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.radius_decay:
          type: range
          bounds: [0.0, 1.0]

strategy:
  name: GLD
  algorithm:
    _target_: evosax.strategies.GLD
    popsize: ${general.popsize}
    num_dims: null
    pholder_params: null
    mean_decay: 0.0
    n_devices: null
  evoparams:
    radius_max: 0.2
    radius_min: 0.001
    radius_decay: 5
    init_min: 0.0
    init_max: 1.0
    clip_min: 0.0
    clip_max: 1.0
