# @package _global_
hydra:
  sweeper:
    ax_config:
      max_trials: 10
      params:
        strategy.algorithm.popsize:
          type: range
          bounds: [10, 100]
        strategy.algorithm.mean_decay:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.sigma_init:
          type: range
          bounds: [0.0, 1.0]

strategy:
  name: LES
  algorithm:
    _target_: evosax.strategies.LES
    popsize: ${general.popsize}
    num_dims: 100 # Default is null but it is required
    pholder_params: null
    net_params: null
    net_ckpt_path: null
    mean_decay: 0.0
    n_devices: null
  evoparams:
    sigma_init: 0.1
    init_min: 0.0
    init_max: 1.0
    clip_min: 0.0
    clip_max: 1.0
