# @package _global_
hydra:
  sweeper:
    ax_config:
      max_trials: 50
      params:
        strategy.algorithm.popsize:
          type: range
          bounds: [10, 100]
        strategy.algorithm.elite_ratio:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.cross_over_rate:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.sigma_init:
          type: range
          bounds: [0.0, 1.0]

strategy:
  name: LGA
  algorithm:
    _target_: evosax.strategies.LGA
    popsize: ${general.popsize}
    num_dims: null
    pholder_params: null
    elite_ratio: 0.47265768330544233
    net_params: null
    net_ckpt_path: null
    n_devices: null
  evoparams:
    cross_over_rate: 0.7413635365664959
    sigma_init: 0.012198401615023613
    init_min: 0.0
    init_max: 1.0
    clip_min: 0.0
    clip_max: 1.0
