# @package _global_
hydra:
  sweeper:
    ax_config:
      max_trials: 50
      params:
        strategy.algorithm.popsize:
          type: range
          bounds: [10, 100]
        strategy.evoparams.inertia_coeff:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.cognitive_coeff:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.social_coeff:
          type: range
          bounds: [0.0, 1.0]

strategy:
  name: PSO
  algorithm:
    _target_: evosax.strategies.PSO
    popsize: ${general.popsize}
    num_dims: null
    pholder_params: null
    n_devices: null
  evoparams:
    inertia_coeff: 1.0
    cognitive_coeff: 0.9263020689534016
    social_coeff: 0.46691079125351337
    init_min: 0.0
    init_max: 1.0
    clip_min: 0.0
    clip_max: 1.0
