# @package _global_
hydra:
  sweeper:
    ax_config:
      max_trials: 10
      params:
        strategy.algorithm.popsize:
          type: range
          bounds: [10, 100]
        strategy.algorithm.elite_ratio:
          type: range
          bounds: [0.0, 1.0]
        strategy.algorithm.memory_size:
          type: range
          bounds: [0.0, 1.0]
        strategy.algorithm.mean_decay:
          type: range
          bounds: [0.0, 1.0]
        # strategy.evoparams.c_cov:
        #   type: range
        #   bounds: [0.0, 1.0]
        # strategy.evoparams.c_c:
        #   type: range
        #   bounds: [0.0, 1.0]
        # strategy.evoparams.c_sigma:
        #   type: range
        #   bounds: [0.0, 1.0]
        # strategy.evoparams.mu_eff:
        #   type: range
        #   bounds: [0.0, 1.0]
        strategy.evoparams.c_m:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.sigma_init:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.sigma_limit:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.t_uncorr:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.q_star:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.c_s:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.d_sigma:
          type: range
          bounds: [0.0, 1.0]

strategy:
  name: RmES
  algorithm:
    _target_: evosax.strategies.RmES
    popsize: ${general.popsize}
    num_dims: null
    pholder_params: null
    elite_ratio: 0.5
    memory_size: 10
    mean_decay: 0.0
    n_devices: null
  evoparams:
    # c_cov: float
    # c_c: float
    # c_sigma: float
    # mu_eff: float
    c_m: 1.0
    sigma_init: 1.0
    sigma_limit: 0.001
    t_uncorr: 20
    q_star: 0.325
    c_s: 0.3
    d_sigma: 1.0
    init_min: 0.0
    init_max: 1.0
    clip_min: 0.0
    clip_max: 1.0
