# @package _global_
hydra:
  sweeper:
    ax_config:
      max_trials: 10
      params:
        strategy.algorithm.popsize:
          type: range
          bounds: [10, 100]
        strategy.algorithm.elite_ratio:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.cross_over_rate:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.sigma_init:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.sigma_decay:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.sigma_limit:
          type: range
          bounds: [0.0, 1.0]

strategy:
  name: SimpleGA
  algorithm:
    _target_: evosax.strategies.SimpleGA
    popsize: ${general.popsize}
    num_dims: null
    pholder_params: null
    elite_ratio: 0.5
    n_devices: null
  evoparams:
    cross_over_rate: 0.0
    sigma_init: 0.07
    sigma_decay: 1.0
    sigma_limit: 0.01
    init_min: 0.0
    init_max: 1.0
    clip_min: 0.0
    clip_max: 1.0
