# @package _global_
hydra:
  sweeper:
    ax_config:
      max_trials: 10
      params:
        strategy.algorithm.popsize:
          type: range
          bounds: [10, 100]
        strategy.algorithm.mean_decay:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.lrate_mean:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.lrate_sigma:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.sigma_init:
          type: range
          bounds: [0.0, 1.0]
        strategy.evoparams.temperature:
          type: range
          bounds: [0.0, 1.0]

strategy:
  name: SNES
  algorithm:
    _target_: evosax.strategies.SNES
    popsize: ${general.popsize}
    num_dims: null
    pholder_params: null
    mean_decay: 0.0
    n_devices: null
  evoparams:
    lrate_mean: 1.0
    lrate_sigma: 1.0
    sigma_init: 1.0
    temperature: 0.0
    init_min: 0.0
    init_max: 1.0
    clip_min: 0.0
    clip_max: 1.0
