name: ctag
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libcxx=14.0.6
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - python=3.9.16
  - pip=22.3.1
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - chex==0.1.7
      - diffusers==0.20.0
      - evosax==0.1.4
      - flax==0.7.1
      - huggingface-hub==0.13.3
      - hydra-core==1.3.2
      - hydra-ax-sweeper==1.2.0
      - ipykernel==6.22.0
      - jax==0.4.14
      - jaxlib==0.4.14
      - jupyter==1.0.0
      - laion-clap==1.1.4
      - librosa==0.10.0.post2
      - matplotlib==3.7.1
      - numba==0.57.0
      - numpy==1.23.5
      - pandas==1.5.3
      - pip==23.2.1
      - progressbar==2.5
      - pydub==0.25.1
      - pyyaml==6.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - soundfile==0.12.1
      - synthax==0.2.0
      - tensorboard==2.13.0
      - torch==2.0.0
      - torchaudio==2.0.1
      - torchvision==0.15.1
      - tqdm==4.65.0
      - transformers==4.27.2
      - umap-learn==0.5.3
      - speechbrain==0.5.15
      # - ax-platform==0.2.8
