#######################
# Auto-configure the CLAP module
#######################

name: clap
ckpt: 630k-fusion-best.pt
model:
    _target_: embedding.CLAPModel
    # Enable fusion if "fusion" is present in the checkpoint
    enable_fusion: true
    # Set the audio model based on the presence of "630k" in the checkpoint
    amodel: HTSAT-tiny
    # Set the text model. Options: ["roberta"]
    tmodel: roberta
    # Checkpoint path
    ckpt_path: ${general.ckpt_path}
    # Model device
    device: ${system.device}