#######################
# Auto-configure the CLAP module
#######################

name: clap
ckpt: music_audioset_epoch_15_esc_90.14.pt
model:
    _target_: embedding.CLAPModel
    # Enable fusion if "fusion" is present in the checkpoint
    enable_fusion: false
    # Set the audio model based on the presence of "630k" in the checkpoint
    amodel: HTSAT-base
    # Set the text model. Options: ["roberta"]
    tmodel: roberta
    # Checkpoint path
    ckpt_path: ${general.ckpt_path}
    # Model device
    device: ${system.device}